name = (TBD1 => tstr) ; "Jane Doe"
given_name = (TBD2 => tstr) ; "Jane"
family_name = (TBD3 => tstr) ; "Doe"
middle_name = (TBD4 => tstr) ; "Ellen"
nickname = (TBD5 => tstr) ; "Jane D."
preferred_username = (TBD6 => tstr) ; "j.doe"
profile = (TBD7 => tstr) ; "https://example.org/about.html"
picture = (TBD8 => tstr) ; "https://example.org/avatar.png"
website = (TBD9 => tstr) ; "https://example.org"
email = (TBD10 => tstr) ; "janedoe@example.com"
email_verified = (TBD11 => tstr) ; "true"
gender = (TBD12 => tstr) ; "female"
birthdate = (TBD13 => tstr) ; "1970-03-22"
zoneinfo = (TBD14 => tstr) ; "America/Los_Angeles"
locale = (TBD15 => tstr) ; "en_US"
phone_number = (TBD16 => tstr) ; "+1 (425) 555-1212"
phone_number_verified = (TBD17 => tstr) ; "true"
address = {
    &(formatted: 1) ^ => tstr, ; "1234 Hollywood Blvd. Los Angeles CA, 90210 United States of America"
    &(street_address: 2) ^ => tstr, ; "1234 Hollywood Blvd."
    &(locality: 3) ^ => tstr, ; "Los Angeles"
    &(region: 4) ^ => tstr, ; "CA"
    &(postal_code: 5) ^ => tstr, ; "90210"
    &(country: 6) ^ => tstr, ; "United States of America"
}
updated_at = (TBD19 => uint) ; 1730123071

TBD1 = 170
TBD2 = 171
TBD3 = 172
TBD4 = 173
TBD5 = 174
TBD6 = 175
TBD7 = 176
TBD8 = 177
TBD9 = 178
TBD10 = 179
TBD11 = 180
TBD12 = 181
TBD13 = 182
TBD14 = 183
TBD15 = 184
TBD16 = 185
TBD17 = 186
TBD18 = 187
TBD19 = 188
