name = (TBD1 => tstr) ; "Jane Doe"
given_name = (TBD2 => tstr) ; "Jane"
family_name = (TBD3 => tstr) ; "Doe"
middle_name = (TBD4 => tstr) ; "Ellen"
nickname = (TBD5 => tstr) ; "Jane D."
preferred_username = (TBD6 => tstr) ; "j.doe"
profile = (TBD7 => tstr) ; "https://example.org/about.html"
picture = (TBD8 => tstr) ; "https://example.org/avatar.png"
website = (TBD9 => tstr) ; "https://example.org"
email = (TBD10 => tstr) ; "janedoe@example.com"
email_verified = (TBD11 => tstr) ; "true"
gender = (TBD12 => tstr) ; "female"
birthdate = (TBD13 => tstr) ; "1970-03-22"
zoneinfo = (TBD14 => tstr) ; "America/Los_Angeles"
locale = (TBD15 => tstr) ; "en_US"
phone_number = (TBD16 => tstr) ; "+1 (425) 555-1212"
phone_number_verified = (TBD17 => tstr) ; "true"
address = (TBD18 => tstr) ; "{"street_address": "1234 Hollywood Blvd.", "locality": "Los Angeles", "region": "CA", "postal_code": "90210", "country": "United States of America"}"
updated_at = (TBD19 => uint) ; 1730123071

TBD1 = 11
TBD2 = 170
TBD3 = 171
TBD4 = 172
TBD5 = 173
TBD6 = 12
TBD7 = 174
TBD8 = 175
TBD9 = 176
TBD10 = 13
TBD11 = 177
TBD12 = 178
TBD13 = 179
TBD14 = 180
TBD15 = 181
TBD16 = 182
TBD17 = 183
TBD18 = 184
TBD19 = 185
